[workspace]
resolver = "3"
members = [
  "monkey-c-config",
  "monkey-c-coverage",
  "monkey-c-formatter",
  "monkey-c-jungle",
  "monkey-c-linter",
  "monkey-c-lsp",
  "monkey-c-parser",
  "rafiki",
]

[workspace.package]
edition = "2024"
version = "0.2.0"
license = "MIT"
repository = "https://github.com/bombsimon/monkey-c-rs"

[workspace.dependencies]
ariadne = "0.6"
clap = { version = "4", features = ["derive"] }
comfy-table = "8"
monkey-c-config = { path = "monkey-c-config", version = "0.2.0" }
monkey-c-coverage = { path = "monkey-c-coverage", version = "0.2.0" }
monkey-c-formatter = { path = "monkey-c-formatter", version = "0.2.0" }
monkey-c-jungle = { path = "monkey-c-jungle" }
monkey-c-linter = { path = "monkey-c-linter", version = "0.2.0" }
monkey-c-lsp = { path = "monkey-c-lsp", version = "0.2.0" }
monkey-c-parser = { path = "monkey-c-parser", version = "0.2.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
