//! Source-level test-coverage instrumentation for Monkey C.
//!
//! The Connect IQ toolchain has no coverage support, so coverage is obtained by rewriting the
//! source before compilation: a `AutoGeneratedCov.hit(N);` call is spliced directly after the
//! opening brace of every function body, a generated `AutoGeneratedCov.mc` runtime prints each id
//! the first time it executes, and a report joins those `COVHIT` lines from the simulator log back
//! to the instrumented functions. Splicing into the original text (rather than re-rendering the
//! AST) keeps untouched code byte-identical.
//!
//! Coverage is function-level only: it reports which functions never run, not which lines or
//! branches, so a fully executed 200-line function counts the same as a one-line one.
//!
//! Declarations annotated with `(:test)` are not instrumented: they only exist in test builds, so
//! counting them would let test code cover itself.

use monkey_c_jungle::ast::{JungleFile, Value};
use monkey_c_parser::ast::Ast;
use monkey_c_parser::line_index::LineIndex;
use monkey_c_parser::parser::{Parser, ParserError};

use std::collections::HashSet;

const DEFAULT_EXCLUDED_ANNOTATIONS: [&str; 2] = ["test", "release"];

/// One instrumented function body: where it lives and the id the runtime
/// reports when it first executes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FunctionSite {
    pub id: usize,
    pub file: String,
    pub name: String,
    pub line: u32,
}

/// The rewritten source of one file plus the sites injected into it.
#[derive(Debug)]
pub struct Instrumented {
    pub source: String,
    pub sites: Vec<FunctionSite>,
}

/// Instrument every function body in `source`, numbering sites from
/// `first_id` so ids stay unique across a multi-file run. `exclude_annotations`
/// names additional annotations (beyond `test` and `release`, which are always
/// excluded) whose declarations should be skipped.
pub fn instrument(
    source: &str,
    file: &str,
    first_id: usize,
    exclude_annotations: &[&str],
) -> Result<Instrumented, ParserError> {
    let output = Parser::new(source).parse()?;
    let mut bodies = Vec::new();
    collect(
        &output.ast,
        exclude_annotations,
        &mut Vec::new(),
        &mut bodies,
    );
    // `collect` walks the AST depth-first, so braces already come out in source
    // order. The splice below runs back-to-front and relies on that; the sort is
    // a cheap guard should the walk order ever change.
    bodies.sort_by_key(|body| body.brace);

    let index = LineIndex::new(source);
    let mut sites = Vec::with_capacity(bodies.len());
    let mut rewritten = String::with_capacity(source.len());
    let mut cursor = 0;

    for (position, body) in bodies.iter().enumerate() {
        let id = first_id + position;
        let after_brace = body.brace + 1;

        rewritten.push_str(&source[cursor..after_brace]);
        rewritten.push_str(&format!(" AutoGeneratedCov.hit({id});"));
        cursor = after_brace;

        sites.push(FunctionSite {
            id,
            file: file.to_string(),
            name: body.name.clone(),
            // LineIndex is 0-indexed; reports follow editor convention.
            line: index.line_col(body.brace as u32).line + 1,
        });
    }

    rewritten.push_str(&source[cursor..]);

    Ok(Instrumented {
        source: rewritten,
        sites,
    })
}

/// The generated runtime module compiled alongside the instrumented source,
/// where `sites` is the total number of instrumented bodies. Ids are dense and
/// start at zero, so a flat `Boolean` array indexed by id is cheaper in the
/// simulator than a `Dictionary`; printing only on the first hit keeps the
/// captured log small.
pub fn runtime_module(sites: usize) -> String {
    // Guard the degenerate zero-site case: `new [0]` is a legal but useless
    // allocation, and a one-slot array keeps the generated module uniform.
    let sites = sites.max(1);
    // The module variable is public and unprefixed so the generated source
    // passes `monkey-c-linter`'s naming rules. Each line is emitted as exactly
    // `COVHIT <id>` — `parse_hits` matches nothing else.
    format!(
        r#"import Toybox.Lang;
import Toybox.System;

// Generated by monkey-c-coverage. Do not edit and do not ship: this module
// exists only in instrumented test builds.
module AutoGeneratedCov {{
    var hits as Array<Boolean?> = new [{sites}];

    function hit(id as Number) as Void {{
        if (hits[id] == null) {{
            hits[id] = true;
            System.println("COVHIT " + id);
        }}
    }}
}}
"#
    )
}

/// Rewrite a project's jungle file for the copy that lives alongside the
/// instrumented sources: `project.manifest` is repointed at `manifest_path`
/// since, unlike `.mc` sources, `manifest.xml` is never copied into the
/// output directory, so a relative reference the original jungle held to it
/// no longer resolves once the jungle moves. Every `sourcePath` gains a `.`
/// entry, if it doesn't already have one, so `monkeyc` also picks up the
/// generated `AutoGeneratedCov.mc` sitting directly in the output directory
/// rather than mirrored under it.
pub fn coverage_jungle(source: &str, manifest_path: &str) -> Result<String, ParserError> {
    let mut jungle = JungleFile::parse(source)?;

    jungle.set("project.manifest", [Value::text(manifest_path)]);

    for assignment in jungle.assignments_mut() {
        if !matches!(assignment.target.property(), [prop] if prop == "sourcePath") {
            continue;
        }

        let has_current_dir = assignment
            .values
            .iter()
            .any(|value| value.to_string() == ".");
        if !has_current_dir {
            assignment.values.push(Value::text("."));
        }
    }

    Ok(jungle.to_string())
}

/// Manifest line format: `id<TAB>line<TAB>file<TAB>name`. TSV keeps the
/// crate dependency-free and the file greppable.
pub fn manifest_line(site: &FunctionSite) -> String {
    format!("{}\t{}\t{}\t{}", site.id, site.line, site.file, site.name)
}

/// Parse one manifest line written by [`manifest_line`] back into a
/// [`FunctionSite`], returning `None` if it doesn't have the four tab-separated
/// fields or the numeric ones don't parse.
pub fn parse_manifest_line(line: &str) -> Option<FunctionSite> {
    let mut parts = line.splitn(4, '\t');
    let id = parts.next()?.parse().ok()?;
    let line_no = parts.next()?.parse().ok()?;
    let file = parts.next()?.to_string();
    let name = parts.next()?.to_string();
    Some(FunctionSite {
        id,
        file,
        name,
        line: line_no,
    })
}

/// Ids reported by the runtime, extracted from a captured simulator log. Only
/// lines that are exactly `COVHIT <id>` once trimmed count; anything the
/// simulator interleaves on other lines is ignored.
pub fn parse_hits(log: &str) -> HashSet<usize> {
    log.lines()
        .filter_map(|line| line.trim().strip_prefix("COVHIT "))
        .filter_map(|id| id.trim().parse().ok())
        .collect()
}

struct FunctionBody {
    brace: usize,
    name: String,
}

fn collect(ast: &Ast, exclude: &[&str], scope: &mut Vec<String>, out: &mut Vec<FunctionBody>) {
    match ast {
        Ast::Document(items, _) => {
            collect_items(items, exclude, scope, out);
        }
        Ast::Module(module) => {
            scope.push(module.name.node.clone());
            collect_items(&module.body, exclude, scope, out);
            scope.pop();
        }
        Ast::Class(class) => {
            scope.push(class.name.node.clone());
            collect_items(&class.body, exclude, scope, out);
            scope.pop();
        }
        Ast::Function(function) => {
            // Abstract and interface declarations have no body to execute.
            if let Some(body) = &function.body {
                out.push(FunctionBody {
                    brace: body.span.start,
                    name: qualified(scope, &function.name.node),
                });
            }
        }
        _ => {}
    }
}

/// Walk sibling declarations, honouring the annotation groups that precede
/// them: a declaration decorated with `(:test)` or another name in `exclude`
/// exists only in test/excluded builds and would otherwise count itself, so it
/// — and everything nested inside it — is left uninstrumented.
fn collect_items(
    items: &[Ast],
    exclude: &[&str],
    scope: &mut Vec<String>,
    out: &mut Vec<FunctionBody>,
) {
    let excluded_annotations: HashSet<&str> = DEFAULT_EXCLUDED_ANNOTATIONS
        .iter()
        .copied()
        .chain(exclude.iter().copied())
        .collect();

    let mut test_annotated = false;

    for item in items {
        // Consecutive groups such as `(:debug) (:test)` all decorate the next
        // declaration, so keep accumulating until one shows up.
        if let Ast::Annotation(entries, _) = item {
            test_annotated |= entries
                .iter()
                .any(|entry| excluded_annotations.contains(entry.name.as_str()));

            continue;
        }

        if !test_annotated {
            collect(item, exclude, scope, out);
        }

        test_annotated = false;
    }
}

fn qualified(scope: &[String], name: &str) -> String {
    if scope.is_empty() {
        return name.to_string();
    }
    format!("{}.{}", scope.join("."), name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn instruments_module_and_class_functions() {
        let source = r#"module M {
    function a() as Void {
        return;
    }
}
class C {
    function b() {
    }
}
"#;
        let result = instrument(source, "x.mc", 0, &[]).unwrap();
        assert_eq!(source.lines().count(), result.source.lines().count());
        assert_eq!(result.sites.len(), 2);
        assert_eq!(result.sites[0].name, "M.a");
        assert_eq!(result.sites[1].name, "C.b");
        assert!(
            result
                .source
                .contains("function a() as Void { AutoGeneratedCov.hit(0);")
        );
        assert!(
            result
                .source
                .contains("function b() { AutoGeneratedCov.hit(1);")
        );

        assert!(
            monkey_c_parser::parser::Parser::new(&result.source)
                .parse()
                .is_ok()
        );
    }

    #[test]
    fn later_files_continue_the_id_sequence() {
        let source = r#"function solo() {
}
"#;
        let result = instrument(source, "y.mc", 7, &[]).unwrap();
        assert_eq!(result.sites[0].id, 7);
        assert!(result.source.contains("AutoGeneratedCov.hit(7);"));
    }

    #[test]
    fn skips_bodyless_declarations() {
        let source = r#"
            class C {
                function abstractLike() as Void;
                function real() {}
            }
        "#;
        let result = instrument(source, "z.mc", 0, &[]).unwrap();
        assert_eq!(result.sites.len(), 1);
        assert_eq!(result.sites[0].name, "C.real");
    }

    #[test]
    fn line_numbers_point_at_the_function_body() {
        let source = r#"function first() {
}

function second() {
}
"#;
        let result = instrument(source, "l.mc", 0, &[]).unwrap();
        assert_eq!(result.sites[0].line, 1);
        assert_eq!(result.sites[1].line, 4);
    }

    #[test]
    fn skips_test_annotated_functions() {
        let source = r#"(:test)
function coversItself(logger) {
    return true;
}

function real() {
}
"#;
        let result = instrument(source, "t.mc", 0, &[]).unwrap();
        assert_eq!(result.sites.len(), 1);
        assert_eq!(result.sites[0].name, "real");
        assert!(
            !result
                .source
                .contains("function coversItself(logger) { AutoGeneratedCov.hit")
        );
    }

    #[test]
    fn skips_everything_inside_test_annotated_containers() {
        let source = r#"(:test)
module Helpers {
    function helper() {
    }
}

(:debug) (:test)
class Stacked {
    function alsoSkipped() {
    }
}

(:background)
function kept() {
}
"#;
        let result = instrument(source, "t.mc", 0, &[]).unwrap();
        assert_eq!(result.sites.len(), 1);
        assert_eq!(result.sites[0].name, "kept");
    }

    #[test]
    fn skips_declarations_with_custom_excluded_annotations() {
        let source = r#"(:background)
function skipped() {
}

function kept() {
}
"#;
        let result = instrument(source, "t.mc", 0, &["background"]).unwrap();
        assert_eq!(result.sites.len(), 1);
        assert_eq!(result.sites[0].name, "kept");
    }

    #[test]
    fn manifest_lines_round_trip() {
        let site = FunctionSite {
            id: 3,
            file: "a.mc".into(),
            name: "M.f".into(),
            line: 12,
        };
        let parsed = parse_manifest_line(&manifest_line(&site)).unwrap();
        assert_eq!(parsed, site);
    }

    #[test]
    fn hits_parse_from_noisy_logs() {
        let log = r#"junk
COVHIT 3
COVHIT 3
something COVHIT 9 inline noise
COVHIT 11
"#;
        let hits = parse_hits(log);
        assert_eq!(hits, HashSet::from([3, 11]));
    }

    #[test]
    fn runtime_module_parses_ok() {
        let runtime = runtime_module(42);
        let parsed = monkey_c_parser::parser::Parser::new(&runtime).parse();
        assert!(parsed.is_ok());

        let linted = monkey_c_linter::lint(&parsed.unwrap(), &runtime);
        assert!(linted.is_empty());
    }

    #[test]
    fn coverage_jungle_repoints_manifest_and_adds_current_dir_to_sources() {
        let source = "project.manifest = manifest.xml\n\nbase.sourcePath = source\nfenix5.sourcePath = $(base.sourcePath);fenix5-source\n";
        let rewritten = coverage_jungle(source, "../../manifest.xml").unwrap();

        assert_eq!(
            rewritten,
            "project.manifest = ../../manifest.xml\n\nbase.sourcePath = source;.\nfenix5.sourcePath = $(base.sourcePath);fenix5-source;.\n"
        );
    }

    #[test]
    fn coverage_jungle_leaves_source_paths_that_already_scan_current_dir() {
        let source = "project.manifest = manifest.xml\nbase.sourcePath = source;.\n";
        let rewritten = coverage_jungle(source, "../../manifest.xml").unwrap();

        assert_eq!(
            rewritten,
            "project.manifest = ../../manifest.xml\nbase.sourcePath = source;.\n"
        );
    }
}
