//! Source-level test-coverage instrumentation for Monkey C.
//!
//! The Connect IQ toolchain has no coverage support, so coverage is obtained
//! by rewriting the source before compilation: a `Cov.hit(N);` call is
//! spliced directly after the opening brace of every function body, a
//! generated `Cov.mc` runtime prints each id the first time it executes, and
//! a report joins those `COVHIT` lines from the simulator log back to the
//! instrumented functions. Splicing into the original text (rather than
//! re-rendering the AST) keeps untouched code byte-identical, the same
//! strategy the linter uses for `--fix`.

use monkey_c_parser::ast::{Ast, BlockStmt, Span};
use monkey_c_parser::line_index::LineIndex;
use monkey_c_parser::parser::{Parser, ParserError};

use std::collections::HashSet;

/// One instrumented function body: where it lives and the id the runtime
/// reports when it first executes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FunctionSite {
    pub id: usize,
    pub file: String,
    pub name: String,
    pub line: u32,
}

/// The rewritten source of one file plus the sites injected into it.
#[derive(Debug)]
pub struct Instrumented {
    pub source: String,
    pub sites: Vec<FunctionSite>,
}

/// Instrument every function body in `source`, numbering sites from
/// `first_id` so ids stay unique across a multi-file run.
pub fn instrument(source: &str, file: &str, first_id: usize) -> Result<Instrumented, ParserError> {
    let output = Parser::new(source).parse()?;
    let mut bodies = Vec::new();
    collect(&output.ast, &mut Vec::new(), &mut bodies);
    // Parse order is not guaranteed to be source order once modules nest, and
    // back-to-front splicing requires descending offsets.
    bodies.sort_by_key(|body| body.brace);

    let index = LineIndex::new(source);
    let mut sites = Vec::new();
    let mut rewritten = source.to_string();
    for (position, body) in bodies.iter().enumerate() {
        sites.push(FunctionSite {
            id: first_id + position,
            file: file.to_string(),
            name: body.name.clone(),
            // LineIndex is 0-indexed; reports follow editor convention.
            line: index.line_col(body.brace as u32).line + 1,
        });
    }
    for site in sites.iter().rev() {
        let brace = bodies[site.id - first_id].brace;
        rewritten.insert_str(brace + 1, &format!(" Cov.hit({});", site.id));
    }

    Ok(Instrumented {
        source: rewritten,
        sites,
    })
}

/// The generated runtime module compiled alongside the instrumented source.
/// A dictionary keeps memory proportional to functions actually executed,
/// and printing only on the first hit keeps the simulator log small.
pub fn runtime_module() -> String {
    r#"import Toybox.Lang;
import Toybox.System;

// Generated by monkey-c-coverage. Do not edit and do not ship: this module
// exists only in instrumented test builds.
module Cov {
    var _hits as Dictionary<Number, Boolean> = ({}) as Dictionary<Number, Boolean>;

    function hit(id as Number) as Void {
        if (!_hits.hasKey(id)) {
            _hits.put(id, true);
            System.println(Lang.format("COVHIT $1$", [id]));
        }
    }
}
"#
    .to_string()
}

/// Manifest line format: `id<TAB>line<TAB>file<TAB>name`. TSV keeps the
/// crate dependency-free and the file greppable.
pub fn manifest_line(site: &FunctionSite) -> String {
    format!("{}\t{}\t{}\t{}", site.id, site.line, site.file, site.name)
}

pub fn parse_manifest_line(line: &str) -> Option<FunctionSite> {
    let mut parts = line.splitn(4, '\t');
    let id = parts.next()?.parse().ok()?;
    let line_no = parts.next()?.parse().ok()?;
    let file = parts.next()?.to_string();
    let name = parts.next()?.to_string();
    Some(FunctionSite {
        id,
        file,
        name,
        line: line_no,
    })
}

/// Ids reported by the runtime, extracted from a captured simulator log.
pub fn parse_hits(log: &str) -> HashSet<usize> {
    log.lines()
        .filter_map(|line| line.trim().strip_prefix("COVHIT "))
        .filter_map(|id| id.trim().parse().ok())
        .collect()
}

struct FunctionBody {
    brace: usize,
    name: String,
}

fn collect(ast: &Ast, scope: &mut Vec<String>, out: &mut Vec<FunctionBody>) {
    match ast {
        Ast::Document(items, _) => {
            for item in items {
                collect(item, scope, out);
            }
        }
        Ast::Module(module) => {
            scope.push(module.name.node.clone());
            for item in &module.body {
                collect(item, scope, out);
            }
            scope.pop();
        }
        Ast::Class(class) => {
            scope.push(class.name.node.clone());
            for item in &class.body {
                collect(item, scope, out);
            }
            scope.pop();
        }
        Ast::Function(function) => {
            // Abstract and interface declarations have no body to execute.
            if let Some(body) = &function.body {
                out.push(FunctionBody {
                    brace: body_brace(body),
                    name: qualified(scope, &function.name.node),
                });
            }
        }
        _ => {}
    }
}

fn body_brace(body: &BlockStmt) -> usize {
    let Span { start, .. } = body.span;
    start
}

fn qualified(scope: &[String], name: &str) -> String {
    if scope.is_empty() {
        return name.to_string();
    }
    format!("{}.{}", scope.join("."), name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn instruments_module_and_class_functions() {
        let source = "module M {\n    function a() as Void {\n        return;\n    }\n}\nclass C {\n    function b() {\n    }\n}\n";
        let result = instrument(source, "x.mc", 0).unwrap();
        assert_eq!(result.sites.len(), 2);
        assert_eq!(result.sites[0].name, "M.a");
        assert_eq!(result.sites[1].name, "C.b");
        assert!(result.source.contains("function a() as Void { Cov.hit(0);"));
        assert!(result.source.contains("function b() { Cov.hit(1);"));
    }

    #[test]
    fn later_files_continue_the_id_sequence() {
        let source = "function solo() {\n}\n";
        let result = instrument(source, "y.mc", 7).unwrap();
        assert_eq!(result.sites[0].id, 7);
        assert!(result.source.contains("Cov.hit(7);"));
    }

    #[test]
    fn skips_bodyless_declarations() {
        let source = r#"
            class C {
                function abstractLike() as Void;
                function real() {}
            }
        "#;
        let result = instrument(source, "z.mc", 0).unwrap();
        assert_eq!(result.sites.len(), 1);
        assert_eq!(result.sites[0].name, "C.real");
    }

    #[test]
    fn line_numbers_point_at_the_function_body() {
        let source = "function first() {\n}\n\nfunction second() {\n}\n";
        let result = instrument(source, "l.mc", 0).unwrap();
        assert_eq!(result.sites[0].line, 1);
        assert_eq!(result.sites[1].line, 4);
    }

    #[test]
    fn manifest_lines_round_trip() {
        let site = FunctionSite {
            id: 3,
            file: "a.mc".into(),
            name: "M.f".into(),
            line: 12,
        };
        let parsed = parse_manifest_line(&manifest_line(&site)).unwrap();
        assert_eq!(parsed, site);
    }

    #[test]
    fn hits_parse_from_noisy_logs() {
        let log = "junk\nCOVHIT 3\nCOVHIT 3\nsomething COVHIT 9 inline noise\nCOVHIT 11\n";
        let hits = parse_hits(log);
        assert_eq!(hits, HashSet::from([3, 11]));
    }
}
