use clap::{Parser, Subcommand};
use monkey_c_coverage::{
    FunctionSite, instrument, manifest_line, parse_hits, parse_manifest_line, runtime_module,
};
use monkey_c_diagnostics::{already_reported, read_source, render_parse_error};

use std::collections::{BTreeMap, HashSet};
use std::fs;
use std::io;
use std::path::{Component, Path, PathBuf};
use std::process::ExitCode;

#[derive(Parser)]
#[command(version, about = "Test-coverage instrumentation for Monkey C")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Rewrite sources with coverage probes into an output directory,
    /// alongside the generated AutoGeneratedCov.mc runtime and the site
    /// manifest.
    Instrument {
        /// Directory that receives the instrumented copies. Cleared on each
        /// run so stale instrumented files never leak into a build.
        #[arg(long, default_value = "bin/coverage")]
        out: PathBuf,
        /// Monkey C source files or directories to instrument.
        files: Vec<PathBuf>,
    },
    /// Join a captured simulator log against the manifest and print
    /// per-file coverage.
    Report {
        /// Directory produced by `instrument`. The report reads the
        /// coverage-manifest.tsv written there together with run.log, the
        /// captured simulator output (e.g. from monkeydo -t).
        #[arg(default_value = "bin/coverage")]
        dir: PathBuf,
    },
}

const MANIFEST_FILE: &str = "coverage-manifest.tsv";
const LOG_FILE: &str = "run.log";

fn main() -> ExitCode {
    let cli = Cli::parse();
    match run(&cli.command) {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            // Parse and invalid-UTF-8 errors are already rendered via ariadne
            // by `render_parse_error` / `read_source`.
            if error.kind() != io::ErrorKind::Other {
                eprintln!("{error}");
            }

            ExitCode::from(1)
        }
    }
}

fn run(command: &Command) -> io::Result<()> {
    match command {
        Command::Instrument { out, files } => run_instrument(out, files),
        Command::Report { dir } => run_report(dir),
    }
}

fn run_instrument(out: &Path, files: &[PathBuf]) -> io::Result<()> {
    let files = collect_mc_files(files)?;
    if files.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "no input files",
        ));
    }

    // A previous run's files would otherwise be recycled into the next
    // build (and report) even after their sources were renamed or removed.
    if out.exists() {
        fs::remove_dir_all(out)?;
    }

    let mut manifest = String::new();
    let mut next_id = 0;
    for file in &files {
        let source = read_source(file)?;
        let dest = mirrored_path(file);
        let name = dest.to_string_lossy().into_owned();
        let result = instrument(&source, &name, next_id).map_err(|e| {
            render_parse_error(&name, &source, &e);
            already_reported()
        })?;
        next_id += result.sites.len();
        for site in &result.sites {
            manifest.push_str(&manifest_line(site));
            manifest.push('\n');
        }
        write(&out.join(&dest), &result.source)?;
    }
    write(&out.join("AutoGeneratedCov.mc"), &runtime_module(next_id))?;
    write(&out.join(MANIFEST_FILE), &manifest)?;
    eprintln!(
        "instrumented {next_id} function bodies across {} files",
        files.len()
    );

    Ok(())
}

/// Resolve `paths` into a deterministic, sorted list of `.mc` files.
/// Files are accepted as-is regardless of extension (so explicit per-file
/// invocations always work); directories are walked recursively, skipping
/// hidden ones. Copied from `monkey-c-formatter` until it grows a shared
/// home.
fn collect_mc_files(paths: &[PathBuf]) -> io::Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    for p in paths {
        let meta = fs::metadata(p)
            .map_err(|e| io::Error::new(e.kind(), format!("{}: {e}", p.display())))?;

        if meta.is_file() {
            files.push(p.clone());
        } else if meta.is_dir() {
            walk_dir(p, &mut files)?;
        } else {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                format!("{}: not a file or directory", p.display()),
            ));
        }
    }

    files.sort();

    Ok(files)
}

fn walk_dir(dir: &Path, out: &mut Vec<PathBuf>) -> io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;

        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name.starts_with('.') {
            continue;
        }

        if file_type.is_dir() {
            walk_dir(&path, out)?;
        } else if file_type.is_file() && path.extension().is_some_and(|e| e == "mc") {
            out.push(path);
        }
    }

    Ok(())
}

fn run_report(dir: &Path) -> io::Result<()> {
    let sites: Vec<FunctionSite> = read_source(&dir.join(MANIFEST_FILE))?
        .lines()
        .filter(|line| !line.is_empty())
        .map(|line| {
            parse_manifest_line(line).ok_or_else(|| {
                io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("bad manifest line: {line}"),
                )
            })
        })
        .collect::<io::Result<_>>()?;
    let hits: HashSet<usize> = parse_hits(&read_source(&dir.join(LOG_FILE))?);

    let mut by_file: BTreeMap<&str, Vec<&FunctionSite>> = BTreeMap::new();
    for site in &sites {
        by_file.entry(&site.file).or_default().push(site);
    }

    let mut total = 0;
    let mut covered = 0;
    println!("{:<36} {:>9}  missed", "file", "covered");
    for (file, file_sites) in &by_file {
        let hit = file_sites.iter().filter(|s| hits.contains(&s.id)).count();
        total += file_sites.len();
        covered += hit;
        let missed: Vec<&str> = file_sites
            .iter()
            .filter(|s| !hits.contains(&s.id))
            .map(|s| s.name.as_str())
            .collect();
        println!(
            "{:<36} {:>4}/{:<4}  {}",
            file,
            hit,
            file_sites.len(),
            missed.join(" ")
        );
    }
    if total == 0 {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "manifest contains no reportable sites",
        ));
    }
    println!(
        "\nTOTAL {covered}/{total} functions executed ({:.0}%)",
        100.0 * covered as f64 / total as f64
    );

    // Zero hits across every site means the instrumented build never ran or its
    // output was not captured — a broken pipeline rather than 0% coverage.
    if covered == 0 {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "no coverage hits in the log — did the instrumented build run and was its output captured?",
        ));
    }

    Ok(())
}

fn write(path: &Path, contents: &str) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| io::Error::new(e.kind(), format!("{}: {e}", parent.display())))?;
    }

    fs::write(path, contents)
        .map_err(|e| io::Error::new(e.kind(), format!("{}: {e}", path.display())))
}

/// Map an input path to the relative path its instrumented copy takes under the
/// output directory. Root, prefix, `.` and `..` components are dropped so
/// distinct sources like `a/foo.mc` and `b/foo.mc` keep separate destinations
/// instead of colliding on `foo.mc`, and nothing escapes the output directory.
fn mirrored_path(path: &Path) -> PathBuf {
    let mut relative = PathBuf::new();
    for component in path.components() {
        if let Component::Normal(part) = component {
            relative.push(part);
        }
    }

    relative
}
