use clap::{Parser as ClapParser, Subcommand};
use monkey_c_coverage::{
    FunctionSite, instrument, manifest_line, parse_hits, parse_manifest_line, runtime_module,
};
use monkey_c_diagnostics::{already_reported, read_source, render_parse_error};

use std::collections::{BTreeMap, HashSet};
use std::fs;
use std::io;
use std::path::{Component, Path, PathBuf};
use std::process::ExitCode;

#[derive(ClapParser)]
#[command(
    name = "monkey-c-coverage",
    about = "Test-coverage instrumentation for Monkey C"
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Rewrite sources with coverage probes into an output directory,
    /// alongside the generated AutoGeneratedCov.mc runtime and the site
    /// manifest.
    Instrument {
        /// Directory that receives the instrumented copies.
        #[arg(long)]
        out: PathBuf,
        /// Monkey C source files to instrument.
        files: Vec<PathBuf>,
    },
    /// Join a captured simulator log against the manifest and print
    /// per-file coverage.
    Report {
        /// Manifest written by `instrument` (coverage-manifest.tsv).
        #[arg(long)]
        manifest: PathBuf,
        /// Simulator output containing COVHIT lines (e.g. from monkeydo -t).
        #[arg(long)]
        log: PathBuf,
        /// Exclude files matching this suffix from the report denominator;
        /// pass e.g. "Test.mc" so test code does not count itself.
        #[arg(long)]
        exclude_suffix: Option<String>,
    },
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    match run(&cli.command) {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            // Parse and invalid-UTF-8 errors are already rendered via ariadne
            // by `render_parse_error` / `read_source`.
            if error.kind() != io::ErrorKind::Other {
                eprintln!("{error}");
            }

            ExitCode::from(1)
        }
    }
}

fn run(command: &Command) -> io::Result<()> {
    match command {
        Command::Instrument { out, files } => run_instrument(out, files),
        Command::Report {
            manifest,
            log,
            exclude_suffix,
        } => run_report(manifest, log, exclude_suffix.as_deref()),
    }
}

fn run_instrument(out: &Path, files: &[PathBuf]) -> io::Result<()> {
    if files.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "no input files",
        ));
    }

    let mut manifest = String::new();
    let mut next_id = 0;
    for file in files {
        let source = read_source(file)?;
        let dest = mirrored_path(file);
        let name = dest.to_string_lossy().into_owned();
        let result = instrument(&source, &name, next_id).map_err(|e| {
            render_parse_error(&name, &source, &e);
            already_reported()
        })?;
        next_id += result.sites.len();
        for site in &result.sites {
            manifest.push_str(&manifest_line(site));
            manifest.push('\n');
        }
        write(&out.join(&dest), &result.source)?;
    }
    write(&out.join("AutoGeneratedCov.mc"), &runtime_module(next_id))?;
    write(&out.join("coverage-manifest.tsv"), &manifest)?;
    eprintln!(
        "instrumented {} function bodies across {} files",
        next_id,
        files.len()
    );

    Ok(())
}

fn run_report(manifest: &Path, log: &Path, exclude_suffix: Option<&str>) -> io::Result<()> {
    let sites: Vec<FunctionSite> = read_source(manifest)?
        .lines()
        .filter(|line| !line.is_empty())
        .map(|line| {
            parse_manifest_line(line).ok_or_else(|| {
                io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("bad manifest line: {line}"),
                )
            })
        })
        .collect::<io::Result<_>>()?;
    let hits: HashSet<usize> = parse_hits(&read_source(log)?);

    let mut by_file: BTreeMap<&str, Vec<&FunctionSite>> = BTreeMap::new();
    for site in &sites {
        if let Some(suffix) = exclude_suffix
            && site.file.ends_with(suffix)
        {
            continue;
        }
        by_file.entry(&site.file).or_default().push(site);
    }

    let mut total = 0;
    let mut covered = 0;
    println!("{:<36} {:>9}  missed", "file", "covered");
    for (file, file_sites) in &by_file {
        let hit = file_sites.iter().filter(|s| hits.contains(&s.id)).count();
        total += file_sites.len();
        covered += hit;
        let missed: Vec<&str> = file_sites
            .iter()
            .filter(|s| !hits.contains(&s.id))
            .map(|s| s.name.as_str())
            .collect();
        println!(
            "{:<36} {:>4}/{:<4}  {}",
            file,
            hit,
            file_sites.len(),
            missed.join(" ")
        );
    }
    if total == 0 {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "manifest contains no reportable sites",
        ));
    }
    println!(
        "\nTOTAL {covered}/{total} functions executed ({:.0}%)",
        100.0 * covered as f64 / total as f64
    );

    // Zero hits across every site means the instrumented build never ran or its
    // output was not captured — a broken pipeline rather than 0% coverage.
    if covered == 0 {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "no coverage hits in the log — did the instrumented build run and was its output captured?",
        ));
    }

    Ok(())
}

fn write(path: &Path, contents: &str) -> io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| io::Error::new(e.kind(), format!("{}: {e}", parent.display())))?;
    }

    fs::write(path, contents)
        .map_err(|e| io::Error::new(e.kind(), format!("{}: {e}", path.display())))
}

/// Map an input path to the relative path its instrumented copy takes under the
/// output directory. Root, prefix, `.` and `..` components are dropped so
/// distinct sources like `a/foo.mc` and `b/foo.mc` keep separate destinations
/// instead of colliding on `foo.mc`, and nothing escapes the output directory.
fn mirrored_path(path: &Path) -> PathBuf {
    let mut relative = PathBuf::new();
    for component in path.components() {
        if let Component::Normal(part) = component {
            relative.push(part);
        }
    }

    relative
}
