use crate::ast::{DoubleLit, FloatLit};

/// Language specification <https://developer.garmin.com/connect-iq/reference-guides/monkey-c-reference>
#[derive(Debug, Clone, PartialEq)]
pub enum Type {
    // Keywords
    AndKeyword,
    As,
    Break,
    Case,
    Catch,
    Class,
    Const,
    Continue,
    Default,
    Do,
    Else,
    Enum,
    Extends,
    Finally,
    For,
    Function,
    Has,
    Hidden,
    If,
    Import,
    InstanceOf,
    Interface,
    Module,
    Native,
    New,
    OrKeyword,
    Private,
    Protected,
    Public,
    Return,
    Static,
    Switch,
    Throw,
    Try,
    Typedef,
    Using,
    Var,
    While,

    // Literals
    /// A hex integer literal, stored as a string to support preserving casing.
    Boolean(bool),
    Char(String),
    Double(DoubleLit),
    Float(FloatLit),
    Hex(String),
    HexLong(String),
    Long(String),
    NaN,
    Null,
    Number(String),
    String(String),

    // Identifiers
    /// The `$` bling symbol — refers to the global namespace.
    Bling,
    Identifier(String),
    Me,
    Self_,
    // Comments
    BlockComment(String),
    Comment(String),

    // Operators
    AddAssign,
    And,
    Assign,
    At,
    Bang,
    BangEqual,
    BitAnd,
    BitAndAssign,
    BitOr,
    BitOrAssign,
    BitXor,
    BitXorAssign,
    LeftShift,
    LeftShiftAssign,
    RightShift,
    RightShiftAssign,
    DivAssign,
    EqualEqual,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    Minus,
    MinusMinus,
    ModAssign,
    MulAssign,
    Or,
    Percent,
    Plus,
    PlusPlus,
    Slash,
    Star,
    SubAssign,
    Tilde,

    // Delimiters
    Colon,
    Comma,
    Dot,
    FatArrow,
    LBrace,
    LBracket,
    LParen,
    Question,
    RBrace,
    RBracket,
    RParen,
    Semicolon,

    // Special
    Eof,
    Illegal,
}

impl std::fmt::Display for Type {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            // Keywords
            Type::AndKeyword => write!(f, "and"),
            Type::As => write!(f, "as"),
            Type::Break => write!(f, "break"),
            Type::Case => write!(f, "case"),
            Type::Catch => write!(f, "catch"),
            Type::Class => write!(f, "class"),
            Type::Const => write!(f, "const"),
            Type::Continue => write!(f, "continue"),
            Type::Default => write!(f, "default"),
            Type::Do => write!(f, "do"),
            Type::Else => write!(f, "else"),
            Type::Enum => write!(f, "enum"),
            Type::Extends => write!(f, "extends"),
            Type::Finally => write!(f, "finally"),
            Type::For => write!(f, "for"),
            Type::Function => write!(f, "function"),
            Type::Has => write!(f, "has"),
            Type::Hidden => write!(f, "hidden"),
            Type::If => write!(f, "if"),
            Type::Import => write!(f, "import"),
            Type::InstanceOf => write!(f, "instanceof"),
            Type::Interface => write!(f, "interface"),
            Type::Module => write!(f, "module"),
            Type::Native => write!(f, "native"),
            Type::New => write!(f, "new"),
            Type::OrKeyword => write!(f, "or"),
            Type::Private => write!(f, "private"),
            Type::Protected => write!(f, "protected"),
            Type::Public => write!(f, "public"),
            Type::Return => write!(f, "return"),
            Type::Static => write!(f, "static"),
            Type::Switch => write!(f, "switch"),
            Type::Throw => write!(f, "throw"),
            Type::Try => write!(f, "try"),
            Type::Typedef => write!(f, "typedef"),
            Type::Using => write!(f, "using"),
            Type::Var => write!(f, "var"),
            Type::While => write!(f, "while"),

            // Literals
            Type::Boolean(b) => write!(f, "{b}"),
            Type::Char(s) => write!(f, "'{s}'"),
            Type::Double(n) => write!(f, "{n}d"),
            Type::Float(n) => write!(f, "{n}"),
            Type::Hex(s) => write!(f, "0x{s}"),
            Type::HexLong(s) => write!(f, "0x{s}l"),
            Type::Long(n) => write!(f, "{n}l"),
            Type::NaN => write!(f, "NaN"),
            Type::Null => write!(f, "null"),
            Type::Number(n) => write!(f, "{n}"),
            Type::String(s) => write!(f, "{s}"),

            // Identifiers
            Type::Bling => write!(f, "$"),
            Type::Identifier(s) => write!(f, "{s}"),
            Type::Me => write!(f, "me"),
            Type::Self_ => write!(f, "self"),
            // Comments
            Type::BlockComment(s) => write!(f, "/*{s}*/"),
            Type::Comment(s) => write!(f, "//{s}"),

            // Operators
            Type::AddAssign => write!(f, "+="),
            Type::And => write!(f, "&&"),
            Type::Assign => write!(f, "="),
            Type::At => write!(f, "@"),
            Type::Bang => write!(f, "!"),
            Type::BangEqual => write!(f, "!="),
            Type::BitAnd => write!(f, "&"),
            Type::BitAndAssign => write!(f, "&="),
            Type::BitOr => write!(f, "|"),
            Type::BitOrAssign => write!(f, "|="),
            Type::BitXor => write!(f, "^"),
            Type::BitXorAssign => write!(f, "^="),
            Type::LeftShift => write!(f, "<<"),
            Type::LeftShiftAssign => write!(f, "<<="),
            Type::RightShift => write!(f, ">>"),
            Type::RightShiftAssign => write!(f, ">>="),
            Type::DivAssign => write!(f, "/="),
            Type::EqualEqual => write!(f, "=="),
            Type::Greater => write!(f, ">"),
            Type::GreaterEqual => write!(f, ">="),
            Type::Less => write!(f, "<"),
            Type::LessEqual => write!(f, "<="),
            Type::Minus => write!(f, "-"),
            Type::MinusMinus => write!(f, "--"),
            Type::ModAssign => write!(f, "%="),
            Type::MulAssign => write!(f, "*="),
            Type::Or => write!(f, "||"),
            Type::Percent => write!(f, "%"),
            Type::Plus => write!(f, "+"),
            Type::PlusPlus => write!(f, "++"),
            Type::Slash => write!(f, "/"),
            Type::Star => write!(f, "*"),
            Type::SubAssign => write!(f, "-="),
            Type::Tilde => write!(f, "~"),

            // Delimiters
            Type::Colon => write!(f, ":"),
            Type::Comma => write!(f, ","),
            Type::Dot => write!(f, "."),
            Type::FatArrow => write!(f, "=>"),
            Type::LBrace => write!(f, "{{"),
            Type::LBracket => write!(f, "["),
            Type::LParen => write!(f, "("),
            Type::Question => write!(f, "?"),
            Type::RBrace => write!(f, "}}"),
            Type::RBracket => write!(f, "]"),
            Type::RParen => write!(f, ")"),
            Type::Semicolon => write!(f, ";"),

            // Special
            Type::Eof => write!(f, "EOF"),
            Type::Illegal => write!(f, "ILLEGAL"),
        }
    }
}

impl std::str::FromStr for Type {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            // Keywords
            "and" => Ok(Type::AndKeyword),
            "as" => Ok(Type::As),
            "break" => Ok(Type::Break),
            "case" => Ok(Type::Case),
            "catch" => Ok(Type::Catch),
            "class" => Ok(Type::Class),
            "const" => Ok(Type::Const),
            "continue" => Ok(Type::Continue),
            "default" => Ok(Type::Default),
            "do" => Ok(Type::Do),
            "else" => Ok(Type::Else),
            "enum" => Ok(Type::Enum),
            "extends" => Ok(Type::Extends),
            "finally" => Ok(Type::Finally),
            "for" => Ok(Type::For),
            "function" => Ok(Type::Function),
            "has" => Ok(Type::Has),
            "hidden" => Ok(Type::Hidden),
            "if" => Ok(Type::If),
            "import" => Ok(Type::Import),
            "instanceof" => Ok(Type::InstanceOf),
            "interface" => Ok(Type::Interface),
            "module" => Ok(Type::Module),
            "native" => Ok(Type::Native),
            "new" => Ok(Type::New),
            "or" => Ok(Type::OrKeyword),
            "private" => Ok(Type::Private),
            "protected" => Ok(Type::Protected),
            "public" => Ok(Type::Public),
            "return" => Ok(Type::Return),
            "static" => Ok(Type::Static),
            "switch" => Ok(Type::Switch),
            "throw" => Ok(Type::Throw),
            "try" => Ok(Type::Try),
            "typedef" => Ok(Type::Typedef),
            "using" => Ok(Type::Using),
            "var" => Ok(Type::Var),
            "while" => Ok(Type::While),

            // Literals
            "true" => Ok(Type::Boolean(true)),
            "false" => Ok(Type::Boolean(false)),
            "NaN" => Ok(Type::NaN),
            "null" => Ok(Type::Null),

            // Identifiers
            "me" => Ok(Type::Me),
            "self" => Ok(Type::Self_),

            // Operators — unreachable from identifier-text lookup, kept for
            // completeness.
            "+=" => Ok(Type::AddAssign),
            "&&" => Ok(Type::And),
            "=" => Ok(Type::Assign),
            "!" => Ok(Type::Bang),
            "!=" => Ok(Type::BangEqual),
            "&" => Ok(Type::BitAnd),
            "&=" => Ok(Type::BitAndAssign),
            "|" => Ok(Type::BitOr),
            "|=" => Ok(Type::BitOrAssign),
            "^" => Ok(Type::BitXor),
            "^=" => Ok(Type::BitXorAssign),
            "<<" => Ok(Type::LeftShift),
            "<<=" => Ok(Type::LeftShiftAssign),
            ">>" => Ok(Type::RightShift),
            ">>=" => Ok(Type::RightShiftAssign),
            "/=" => Ok(Type::DivAssign),
            "==" => Ok(Type::EqualEqual),
            ">" => Ok(Type::Greater),
            ">=" => Ok(Type::GreaterEqual),
            "<" => Ok(Type::Less),
            "<=" => Ok(Type::LessEqual),
            "-" => Ok(Type::Minus),
            "--" => Ok(Type::MinusMinus),
            "%=" => Ok(Type::ModAssign),
            "*=" => Ok(Type::MulAssign),
            "||" => Ok(Type::Or),
            "%" => Ok(Type::Percent),
            "+" => Ok(Type::Plus),
            "++" => Ok(Type::PlusPlus),
            "/" => Ok(Type::Slash),
            "*" => Ok(Type::Star),
            "-=" => Ok(Type::SubAssign),
            "~" => Ok(Type::Tilde),

            // Delimiters — unreachable from identifier-text lookup.
            ":" => Ok(Type::Colon),
            "," => Ok(Type::Comma),
            "." => Ok(Type::Dot),
            "=>" => Ok(Type::FatArrow),
            "{" => Ok(Type::LBrace),
            "[" => Ok(Type::LBracket),
            "(" => Ok(Type::LParen),
            "?" => Ok(Type::Question),
            "}" => Ok(Type::RBrace),
            "]" => Ok(Type::RBracket),
            ")" => Ok(Type::RParen),
            ";" => Ok(Type::Semicolon),

            _ => Err(format!("Unknown token: {s}")),
        }
    }
}
