[package]
name = "monkey-c-formatter"
description = "Formatter for the Monkey C language"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
monkey-c-parser.workspace = true

[dev-dependencies]
insta = { version = "1", features = ["glob"] }
