[package]
name = "monkey-c-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[example]]
name = "speed_converter"
path = "examples/speed_converter.rs"

[dependencies]
