---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: fmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --workspace --all-features --tests -- -D warnings

      - name: doc
        env:
          RUSTDOCFLAGS: "-D warnings"
        run: cargo doc --workspace --all-features --keep-going

      - name: test
        run: cargo test --workspace --all-features
